plugin_blacklist: []
# common
##- safety_area
# extras
##- image_pub
##- vibration
##- distance_sensor
##- rangefinder
##- wheel_odometry

plugin_whitelist:
- global_position
- sys_time
- local_position
- imu_pub
- sys_status
# 'sys_*'

